ALTER TABLE "User"
ADD COLUMN "showPublicPosts" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "showPublicComments" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "showPublicPets" BOOLEAN NOT NULL DEFAULT true;
