ALTER TYPE "AuthAuditAction" ADD VALUE IF NOT EXISTS 'REGISTER_SUCCESS';
ALTER TYPE "AuthAuditAction" ADD VALUE IF NOT EXISTS 'REGISTER_REJECTED';
ALTER TYPE "AuthAuditAction" ADD VALUE IF NOT EXISTS 'REGISTER_RATE_LIMITED';
