ALTER TYPE "ModerationTargetType" ADD VALUE IF NOT EXISTS 'SYSTEM';

ALTER TYPE "ModerationActionType" ADD VALUE IF NOT EXISTS 'POLICY_UPDATED';
ALTER TYPE "ModerationActionType" ADD VALUE IF NOT EXISTS 'AUTH_AUDIT_VIEWED';
ALTER TYPE "ModerationActionType" ADD VALUE IF NOT EXISTS 'AUTH_AUDIT_EXPORTED';
